#GROQ_API_KEY = "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"
GROQ_API_KEY = "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"
OPENAI_API_KEY = "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"
ANTHROPIC_API_KEY = "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"
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_API_KEY = "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"
LANGCHAIN_PROJECT = "inflera-demo-test"
PRIVATE_KEY = """MIIEpAIBAAKCAQEAwSrJW532uKcy096Sq2e22AMtZjMHkbngNoEpv4ebr+KnQgNX
AmcPt18a4Smj+dwpTPGJ6Wz9EzfhEmv6M9tPWxiNF69rfeDY1HgNKo9miuMraqzu
Epm5fTKUQYIg5TQKjypeceADjhRPkan9PL7T+BzUvBCUcuIJgp4XE09pb8rfYIiu
Da09MPc4VKRmkKyMgCws58F/OV3WFoYQm3Ujsj7lkCx90JwHYTpHe7bhafl5xA4H
tm8ihpSJaIpDh3K6gQ2+g/DN/eOqinBt0aLZZv1ZwdYU7IDS1AZwo7Au/PeNSiH8
4u5oeEseC5mb/60pyEFGM+tHqCSDrLo3eIK3FQIDAQABAoIBAQC9VF2V8ccAB8kW
xsHFRNt+7+ZQlFWn7KKpaYHs21KqWyIK3tEqZq+N0Ka86J5y6OqGIvxEkXGfo5Z0
AudyalNmezLXczWNZJPB9IUbIQClwrEsVqDmFEwtPST47D2nyZFL74AwZxu0541x
vUabgoKqXj/YsPt/erNNlfwSDjTOvzmvashcrorb0z7R64MJ5aPeh4F36sO7zf+G
rxfMHFKXHq4PIYLcYSCclui/ujP50j84SJpa57jn595Jm8HSEDZ1BCsi1hVdob6U
rjITR43l+ipELQm0xfN4RsInSB7o75sFUaLPy4iIasxRwHDEhTj9ZPO8F27ZhvhR
Yol8sDjFAoGBAO4a/bqXEmJsoRC6NzaOy1eUHQyPAegv1kmpX1HJN7VP0/kWJIZQ
ISZO5tGqo68Pg0cwMWidO2d218bP328VV1X2bqSFi4fEfHjMcCYf8xS1tbxNn6QE
hNY0uRw94MVHu5Gw0BqryCDVYky9GdvJl2mlNoi0HBDVX3foCjTsZtsXAoGBAM+v
NXtTmhA0i0sCMTIrddeGPU0CTQct3n73DvmJbksAJ0V8kk6PA8GyKDSoTAJfmhj7
QDmmH9MWNNzEL/SQg+UawPXqCJLqb8YhsiforZuIk7LetVn8sphmv7IuYXGmis0z
mkwXypI+HDjO8sY+yf6iCCpInIdLxiyoes1FIGqzAoGAdQufnpGU3/02T9q6OX+I
RczxWrMR5OlfFWbFDJc1Y1OSh+dynPPW19YBcR/Ixs2BYwU1xI9GHF43Q+v7kceT
3xX83bMoG91isp8MojEidRO9+orN5vqxsfrI5DEmxNO2SK/6HKJFBp7ea4qpo3k9
jRlB7YFcKoo5G+Bc5BcxmJECgYAFETJN2wFUSePoJZqLrdHHO2g9e8PjW/QkxuRf
pEHDpLJQmLR9JDIkRLOEbWLFYA3DdEXh4jK+lLkfdc3xuqDtMxToKxigdQXbILFX
Fe8+bzujTpnAI1E8NK2SrF0GR9j1HsAyARaZMNjBbhMwURHem5d1aKYhCvE/37B3
V6ttzwKBgQCIttS5Kb+IRbg5r5BPid+RNR1PpswXEntJsuvcpOyJVJPM4SvAZN73
HP8xOlkAkGlzzWABIcVFnR1/KgzdohegDqF2Nd8OuPRaNkAaF15nz2uyLABzs9qa
V1uCqg8yvgol37wIZ6Sg4Q+1wnyPxPnMnFcrfyDgoK2tDrU+EhuTeg=="""
WASABI_ACCESS_KEY = "RU0CG0MBTEV6JH71OMBW"
WASABI_SECRET_KEY = "ZzLMWPM10B1BQT0MKbiKyC9de9mMZjgBo0mBbbdv"
GOOGLE_API_KEY = "AIzaSyBuJHPmV15ljUhQsK_dCeD-WYfnjNmYpcg"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.0ut2SEDBIzVEB31UBxPD9qNnMvB67qbPt18ARXp5nt0"
ASTRADB_ENDPOINT = "https://1a6dede5-1171-41f9-be70-7c6864b4d25e-us-east-2.apps.astra.datastax.com"
ASTRADB_TOKEN = "AstraCS:HYJFIhuJLSsyICHZqcJJnxRB:73d7a4670a9e4551a9f7d16cd3047623d042698b0bb8fa23df947255777a7e9b"
VECTORX_API_TOKEN="10kwijyf:zkUS9ikRh52thZdSSwTNzJLkB5ayHHvE:iw1"