#GROQ_API_KEY = "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"
GROQ_API_KEY = "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"
OPENAI_API_KEY = "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"
ANTHROPIC_API_KEY = "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"
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_API_KEY = "lsv2_pt_45122bc3f5614e7e95e4b8d63e85578d_285e09d07flsv2_pt_26a5883d2ff748359e15ac635a875752_1dfdd6a2ef"
LANGCHAIN_PROJECT = "test-project"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.0ut2SEDBIzVEB31UBxPD9qNnMvB67qbPt18ARXp5nt0"
